In [1]:
import os
cwd = os.getcwd()
cwd

'/Users/diiru/Desktop/Santander/codigo'

In [2]:
import sqlite3 as lite
import pandas
import matplotlib.pyplot as plt
import os

In [3]:
# Coneccion bd
filename = '/Users/diiru/Desktop/Santander'
conector = lite.connect(filename+ ".db")

In [4]:
# Leer archivo
df_cliente_pyme = pandas.read_excel('../Pyme/Proyecto_PreciosPyme_Base1.xlsx')

In [5]:
df_cliente_pyme

,Periodo,fec_info,rut_clie,nom_clie,cli_cat,nom_cli_cat,id_univ,cli_cat_sub,nom_sub_cat,opers,...,MON9,MON10,MON11,MON12,MON13,MON14,MON15,MON16,Suma Var,Var pos neg
0,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059552984,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
1,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584066,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
2,201605,20160531,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000058435660,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
3,201603,20160331,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000056851304,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
4,201605,20160531,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000058379500,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
5,201607,20160729,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059049246,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
6,201603,20160331,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000057264521,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
7,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584081,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
8,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059552987,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
9,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584080,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
10,201604,20160429,76016081,INGENIERIA Y MAESTRANZA DEL NORTE S A,820,Pyme,Pyme 1,826,Pyme 1 PJ Comercio,420016914818,...,704885,-244692,-5868301,4841896,374896,-385750,-373083,0,-745303,NEG
11,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059552986,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
12,201607,20160729,76016081,INGENIERIA Y MAESTRANZA DEL NORTE S A,820,Pyme,Pyme 1,826,Pyme 1 PJ Comercio,420016914818,...,704885,-244692,-5868301,4841896,374896,-385750,-373083,0,-745303,NEG
13,201603,20160331,76016150,GUSTAVO QUEZADA Y COMPANIA LIMITADA,810,Negocio,Negocio,812,Negocios PJ,420016858730,...,-33834,-10109,35980,44992,-36824,-15599,-35921,-3714,-259129,NEG
14,201609,20160930,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000060291924,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
15,201609,20160930,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000060291923,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
16,201603,20160331,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000056851303,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
17,201704,20170428,76016097,SERVICIOS MED ODONTO STA ANGELA LTDA,820,Pyme,Pyme 2,824,Pyme 2 PJ,500007224128,...,-16997,35134,-64305,14375,-52335,33908,-9754,-32035,-119386,NEG
18,201606,20160630,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000058968876,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
19,201605,20160531,76016114,GENESIS CONSTR MONT Y SERV MEC LIMITADA,820,Pyme,Pyme 2,824,Pyme 2 PJ,550008383413,...,321674,341110,-677225,-47054,-221912,43348,223343,-118406,352673,POSIT
20,201610,20161028,76016114,GENESIS CONSTR MONT Y SERV MEC LIMITADA,820,Pyme,Pyme 2,824,Pyme 2 PJ,550008716358,...,321674,341110,-677225,-47054,-221912,43348,223343,-118406,352673,POSIT
21,201605,20160531,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000058379498,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
22,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059552985,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
23,201609,20160930,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000060258586,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
24,201607,20160729,76016114,GENESIS CONSTR MONT Y SERV MEC LIMITADA,820,Pyme,Pyme 2,824,Pyme 2 PJ,550008538719,...,321674,341110,-677225,-47054,-221912,43348,223343,-118406,352673,POSIT
25,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584071,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
26,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584079,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
27,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584078,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
28,201608,20160831,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000059584077,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
29,201603,20160331,76101090,SOCIEDAD AGUAS CLARAS LIMITADA,820,Pyme,Pyme 2,828,Pyme 2 PJ Comercio,000057093436,...,2942,686746,-892998,-110864,-95583,-327674,-168947,60070,869188,POSIT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108646,201612,20161230,200505517,ECUATECXXIS S A,820,Pyme,Pyme 2,824,Pyme 2 PJ,000F87301301,...,-530537,-1022320,850655,-568210,-696805,-988673,-1305349,0,-3314543,NEG
108647,201605,20160531,200505517,ECUATECXXIS S A,820,Pyme,Pyme 2,824,Pyme 2 PJ,00000F883849,...,-530537,-1022320,850655,-568210,-696805,-988673,-1305349,0,-3314543,NEG
108648,201612,20161230,200509540,SOC DE NEGOCIOS E INV INMOB LA PALMA SA,820,Pyme,Pyme,801,Pyme s/s,00000F890903,...,0,0,0,0,0,-14811291,15351967,-498088,42588,POSIT
108649,201605,20160531,405587340,NATEXIS BANQUES POPULAIRES,820,Pyme,Pyme,801,Pyme s/s,00000F883915,...,0,0,0,0,0,0,0,0,0,NEG
108650,201606,20160630,443730440,KEB HANA BANK,820,Pyme,Pyme,801,Pyme s/s,00000E531067,...,0,0,0,0,0,0,0,0,0,NEG
108651,201603,20160331,452660276,COMMERZBANK AG LONDON GB,820,Pyme,Pyme,801,Pyme s/s,00000E530681,...,0,0,0,0,0,0,0,0,0,NEG
108652,201609,20160930,452660276,COMMERZBANK AG LONDON GB,820,Pyme,Pyme,801,Pyme s/s,00000E531502,...,0,0,0,0,0,0,0,0,0,NEG
108653,201602,20160229,452660276,COMMERZBANK AG LONDON GB,820,Pyme,Pyme,801,Pyme s/s,00000E530531,...,0,0,0,0,0,0,0,0,0,NEG
108654,201606,20160630,452835340,NATIXIS FORMERLY NATEXIS BANQUES POPULAR,820,Pyme,Pyme,801,Pyme s/s,00000F884938,...,0,0,0,0,0,0,0,0,0,NEG
108655,201603,20160331,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855100405577,...,0,0,0,0,0,0,0,0,0,NEG
108656,201601,20160129,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855100404449,...,0,0,0,0,0,0,0,0,0,NEG
108657,201603,20160331,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855100405577,...,0,0,0,0,0,0,0,0,0,NEG
108658,201604,20160429,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855200406252,...,0,0,0,0,0,0,0,0,0,NEG
108659,201601,20160129,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855100404449,...,0,0,0,0,0,0,0,0,0,NEG
108660,201603,20160331,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855200405817,...,0,0,0,0,0,0,0,0,0,NEG
108661,201603,20160331,453183276,HSBC BANK PLC LONDON,820,Pyme,Pyme,801,Pyme s/s,855200405817,...,0,0,0,0,0,0,0,0,0,NEG
108662,201608,20160831,456070052,MACQUARIE BANK LIMITED SYDNEY,820,Pyme,Pyme,801,Pyme s/s,00000E531390,...,0,0,0,0,0,0,0,0,0,NEG
108663,201610,20161028,456084052,MIZUHO CORPORATE BANK LTD SYDNEY,820,Pyme,Pyme,801,Pyme s/s,855200412279,...,0,0,0,7798460,-7798460,0,0,0,0,NEG
108664,201603,20160331,456647200,LUZERNER KANTONALBANK LUCERNE,820,Pyme,Pyme,801,Pyme s/s,00000J901461,...,0,0,0,0,0,0,0,0,0,NEG
108665,201602,20160229,462196708,CREDIT AGRICOLE CIB SINGAPORE,820,Pyme,Pyme,801,Pyme s/s,00000E530537,...,0,0,0,0,0,0,0,0,0,NEG
108666,201605,20160531,462196708,CREDIT AGRICOLE CIB SINGAPORE,820,Pyme,Pyme,801,Pyme s/s,00000E530884,...,0,0,0,0,0,0,0,0,0,NEG
108667,201612,20161230,462202708,COMMONWEALTH BANK OF AUSTRALIA SINGAPOR,820,Pyme,Pyme,801,Pyme s/s,00000F891610,...,0,0,0,0,0,0,0,0,0,NEG
108668,201602,20160229,465183212,NYKREDIT BANK A/S,820,Pyme,Pyme,801,Pyme s/s,00000J901444,...,0,0,0,0,0,0,0,0,0,NEG
108669,201606,20160630,467617340,SHINHAN BANK HONG KONG BRANCH,820,Pyme,Pyme,801,Pyme s/s,00000F884989,...,0,0,0,0,0,0,0,0,0,NEG
108670,201607,20160729,469045512,STANDARD CHARTERED BANK MACAU,820,Pyme,Pyme,801,Pyme s/s,00000E531115,...,0,0,0,0,0,0,0,0,0,NEG
108671,201612,20161230,470394708,SOCIETE GENERALE SINGAPORE,820,Pyme,Pyme,801,Pyme s/s,00000E531842,...,0,0,0,0,0,0,0,0,0,NEG
108672,201609,20160930,470394708,SOCIETE GENERALE SINGAPORE,820,Pyme,Pyme,801,Pyme s/s,00000E531424,...,0,0,0,0,0,0,0,0,0,NEG
108673,201609,20160930,490016172,BCO BILBAO VIZCAYA ARGENTARIA COLOMBIA S,820,Pyme,Pyme,801,Pyme s/s,00000E531423,...,0,0,0,0,0,0,0,0,0,NEG
108674,201602,20160229,496067168,BANCO SANTANDER S A BEIJING BRANCH,820,Pyme,Pyme,801,Pyme s/s,855100404988,...,0,0,0,0,0,0,0,0,0,NEG
108675,201604,20160429,496072052,BANCO SANTANDER S A SYDNEY BRANCH,820,Pyme,Pyme,801,Pyme s/s,855100406298,...,0,0,0,0,0,0,0,0,0,NEG

In [8]:
df_cliente_pyme.to_sql('SantanderFinal', conector)

/Users/diiru/anaconda/lib/python3.5/site-packages/pandas/core/generic.py:1345: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [6]:
from sklearn.linear_model import LinearRegression

In [9]:
len(df_cliente_pyme)

108676

In [10]:
list(df_cliente_pyme)

['Periodo',
 'fec_info',
 'rut_clie',
 'nom_clie',
 'cli_cat',
 'nom_cli_cat',
 'id_univ',
 'cli_cat_sub',
 'nom_sub_cat',
 'opers',
 'fec_otorg',
 'año_otorg',
 'mes_otorg',
 'dia_otorg',
 'zona_nueva',
 'Zonal',
 'grp_suc',
 'mto_otorg',
 'cta_actual',
 'cod_ctr',
 'rut_ejec_gest',
 'nom_ejec_gest',
 'cargo_ejec_gest_rrhh',
 'cargo_conc_gest',
 'suc_gest_ejec',
 'nom_suc_gest',
 'zona_nueva_gest',
 'id_orden_prod',
 'id_prod_conc',
 'extin_cdto',
 'plazo_meses',
 'tasa_act',
 'tasa_transf',
 'Tipo_conta',
 'spread',
 'margen_b',
 'id_plazo',
 'id_tramo',
 'id_tasa',
 'grp',
 'NOM_GRP',
 'tasa_0',
 'tasa_1',
 'tasa_1_tarifado',
 'modelo_id_riesgo',
 'perfil_riesgo',
 'ajuste_max',
 'descuento',
 'plazo',
 'tramo',
 'n_cuotas_pact',
 'plazos_dias',
 'tipo_flujo',
 'fecha_otorgamiento',
 'tipo_camb_reaj',
 'tipo_camb_mx',
 'prod_gsc',
 'peso_ctr',
 'plan',
 'concepto_especifico',
 'Marca_Conta',
 'Marca_Campaña',
 'Marca_Renegociados',
 'Marca_Alivio',
 'Marca_Carterizado',
 'MarcaCanal',
 'MarcaFFVV',
 'Tasa*mto',
 'Spread*mto',
 'GLOSA CODIGO ACTIVIDAD BANCO',
 'GLOSA ACTIVIDAD CIIU',
 'AÑO_APERTURA_SA',
 'MES_APERTURA_SA',
 'RUT_CORTO',
 'Octubre 2015_MOB',
 'Noviembre 2015_MOB',
 'Diciembre 2015_MOB',
 'Enero 2016_MOB',
 'Febrero 2016_MOB',
 'Marzo 2016_MOB',
 'Abril 2016_MOB',
 'Mayo 2016_MOB',
 'Junio 2016_MOB',
 'Julio 2016_MOB',
 'Agosto 2016_MOB',
 'FAM_201609_MOB',
 'FAM_201610_MOB',
 'FAM_201611_MOB',
 'FAM_201612_MOB',
 'FAM_201701_MOB',
 'FAM_201702_MOB',
 'Octubre 2015_LdN_ACT_SM',
 'Noviembre 2015_LdN_ACT_SM',
 'Diciembre 2015_LdN_ACT_SM',
 'Enero 2016_LdN_ACT_SM',
 'Febrero 2016_LdN_ACT_SM',
 'Marzo 2016_LdN_ACT_SM',
 'Abril 2016_LdN_ACT_SM',
 'Mayo 2016_LdN_ACT_SM',
 'Junio 2016_LdN_ACT_SM',
 'Julio 2016_LdN_ACT_SM',
 'Agosto 2016_LdN_ACT_SM',
 'FAM_201609_LdN_ACT_SM',
 'FAM_201610_LdN_ACT_SM',
 'FAM_201611_LdN_ACT_SM',
 'FAM_201612_LdN_ACT_SM',
 'FAM_201701_LdN_ACT_SM',
 'FAM_201702_LdN_ACT_SM',
 'Octubre 2015_LdN_PAS_SM',
 'Noviembre 2015_LdN_PAS_SM',
 'Diciembre 2015_LdN_PAS_SM',
 'Enero 2016_LdN_PAS_SM',
 'Febrero 2016_LdN_PAS_SM',
 'Marzo 2016_LdN_PAS_SM',
 'Abril 2016_LdN_PAS_SM',
 'Mayo 2016_LdN_PAS_SM',
 'Junio 2016_LdN_PAS_SM',
 'Julio 2016_LdN_PAS_SM',
 'Agosto 2016_LdN_PAS_SM',
 'FAM_201609_LdN_PAS_SM',
 'FAM_201610_LdN_PAS_SM',
 'FAM_201611_LdN_PAS_SM',
 'FAM_201612_LdN_PAS_SM',
 'FAM_201701_LdN_PAS_SM',
 'FAM_201702_LdN_PAS_SM',
 'Octubre 2015_IND_CTA_CTA',
 'Noviembre 2015_IND_CTA_CTA',
 'Diciembre 2015_IND_CTA_CTA',
 'Enero 2016_IND_CTA_CTA',
 'Febrero 2016_IND_CTA_CTA',
 'Marzo 2016_IND_CTA_CTA',
 'Abril 2016_IND_CTA_CTA',
 'Mayo 2016_IND_CTA_CTA',
 'Junio 2016_IND_CTA_CTA',
 'Julio 2016_IND_CTA_CTA',
 'Agosto 2016_IND_CTA_CTA',
 'FAM_201609_IND_CTA_CTA',
 'FAM_201610_IND_CTA_CTA',
 'FAM_201611_IND_CTA_CTA',
 'FAM_201612_IND_CTA_CTA',
 'FAM_201701_IND_CTA_CTA',
 'FAM_201702_IND_CTA_CTA',
 'Octubre 2015_MON',
 'Noviembre 2015_MON',
 'Diciembre 2015_MON',
 'Enero 2016_MON',
 'Febrero 2016_MON',
 'Marzo 2016_MON',
 'Abril 2016_MON',
 'Mayo 2016_MON',
 'Junio 2016_MON',
 'Julio 2016_MON',
 'Agosto 2016_MON',
 'FAM_201609_MON',
 'FAM_201610_MON',
 'FAM_201611_MON',
 'FAM_201612_MON',
 'FAM_201701_MON',
 'FAM_201702_MON',
 'Octubre 2015_LdN_COMI',
 'Noviembre 2015_LdN_COMI',
 'Diciembre 2015_LdN_COMI',
 'Enero 2016_LdN_COMI',
 'Febrero 2016_LdN_COMI',
 'Marzo 2016_LdN_COMI',
 'Abril 2016_LdN_COMI',
 'Mayo 2016_LdN_COMI',
 'Junio 2016_LdN_COMI',
 'Julio 2016_LdN_COMI',
 'Agosto 2016_LdN_COMI',
 'FAM_201609_LdN_COMI',
 'FAM_201610_LdN_COMI',
 'FAM_201611_LdN_COMI',
 'FAM_201612_LdN_COMI',
 'FAM_201701_LdN_COMI',
 'FAM_201702_LdN_COMI',
 'Octubre 2015_LdN_ACT_RESTO_CREDITO_SM',
 'Noviembre 2015_LdN_ACT_RESTO_CREDITO_SM',
 'Diciembre 2015_LdN_ACT_RESTO_CREDITO_SM',
 'Enero 2016_LdN_ACT_RESTO_CREDITO_SM',
 'Junio 2016_LdN_ACT_RESTO_CREDITO_SM',
 'Julio 2016_LdN_ACT_RESTO_CREDITO_SM',
 'Agosto 2016_LdN_ACT_RESTO_CREDITO_SM',
 'FAM_201609_LdN_ACT_RESTO_CREDITO_SM',
 'FAM_201610_LdN_ACT_RESTO_CREDITO_SM',
 'FAM_201611_LdN_ACT_RESTO_CREDITO_SM',
 'FAM_201612_LdN_ACT_RESTO_CREDITO_SM',
 'FAM_201701_LdN_ACT_RESTO_CREDITO_SM',
 'FAM_201702_LdN_ACT_RESTO_CREDITO_SM',
 'Febrero 2016_LdN_ACT_RESTO_CREDITO_MG',
 'Marzo 2016_LdN_ACT_RESTO_CREDITO_MG',
 'Junio 2016_LdN_ACT_RESTO_CREDITO_MG',
 'Julio 2016_LdN_ACT_RESTO_CREDITO_MG',
 'Agosto 2016_LdN_ACT_RESTO_CREDITO_MG',
 'FAM_201609_LdN_ACT_RESTO_CREDITO_MG',
 'FAM_201610_LdN_ACT_RESTO_CREDITO_MG',
 'FAM_201611_LdN_ACT_RESTO_CREDITO_MG',
 'FAM_201612_LdN_ACT_RESTO_CREDITO_MG',
 'FAM_201701_LdN_ACT_RESTO_CREDITO_MG',
 'FAM_201702_LdN_ACT_RESTO_CREDITO_MG',
 'Junio 2016_LdN_ACT_MG',
 'Julio 2016_LdN_ACT_MG',
 'Agosto 2016_LdN_ACT_MG',
 'FAM_201609_LdN_ACT_MG',
 'FAM_201610_LdN_ACT_MG',
 'FAM_201611_LdN_ACT_MG',
 'FAM_201612_LdN_ACT_MG',
 'FAM_201701_LdN_ACT_MG',
 'FAM_201702_LdN_ACT_MG',
 'FAM_201609_LdN_ACT_Factoring_MG',
 'FAM_201610_LdN_ACT_Factoring_MG',
 'FAM_201611_LdN_ACT_Factoring_MG',
 'FAM_201612_LdN_ACT_Factoring_MG',
 'FAM_201701_LdN_ACT_Factoring_MG',
 'FAM_201702_LdN_ACT_Factoring_MG',
 'FAM_201609_LdN_ACT_Descubiertos_MG',
 'FAM_201610_LdN_ACT_Descubiertos_MG',
 'FAM_201611_LdN_ACT_Descubiertos_MG',
 'FAM_201612_LdN_ACT_Descubiertos_MG',
 'FAM_201701_LdN_ACT_Descubiertos_MG',
 'FAM_201702_LdN_ACT_Descubiertos_MG',
 'FAM_201609_LdN_ACT_Factoring_SM',
 'FAM_201610_LdN_ACT_Factoring_SM',
 'FAM_201611_LdN_ACT_Factoring_SM',
 'FAM_201612_LdN_ACT_Factoring_SM',
 'FAM_201701_LdN_ACT_Factoring_SM',
 'FAM_201702_LdN_ACT_Factoring_SM',
 'FAM_201609_LdN_ACT_Descubiertos_SM',
 'FAM_201610_LdN_ACT_Descubiertos_SM',
 'FAM_201611_LdN_ACT_Descubiertos_SM',
 'FAM_201612_LdN_ACT_Descubiertos_SM',
 'FAM_201701_LdN_ACT_Descubiertos_SM',
 'FAM_201702_LdN_ACT_Descubiertos_SM',
 'Junio 2016_LdN_PAS_MG',
 'Julio 2016_LdN_PAS_MG',
 'Agosto 2016_LdN_PAS_MG',
 'FAM_201609_LdN_PAS_MG',
 'FAM_201610_LdN_PAS_MG',
 'FAM_201611_LdN_PAS_MG',
 'FAM_201612_LdN_PAS_MG',
 'FAM_201701_LdN_PAS_MG',
 'FAM_201702_LdN_PAS_MG',
 '% Descuento',
 'Tramo Tasa',
 'Tramo ACTSM1',
 'Tramo ACTSM2',
 'Tramo ACTSM3',
 'Tramo ACTSM4',
 'Tramo ACTSM5',
 'Tramo ACTSM6',
 'Tramo ACTSM7',
 'Tramo ACTSM8',
 'Tramo ACTSM9',
 'Tramo ACTSM10',
 'Tramo ACTSM11',
 'Tramo ACTSM12',
 'Tramo ACTSM13',
 'Tramo ACTSM14',
 'Tramo ACTSM15',
 'Tramo ACTSM16',
 'Tramo ACTSM17',
 'CONCSMACT',
 'Media_SM',
 'MON PROM',
 'MON1',
 'MON2',
 'MON3',
 'MON4',
 'MON5',
 'MON6',
 'MON7',
 'MON8',
 'MON9',
 'MON10',
 'MON11',
 'MON12',
 'MON13',
 'MON14',
 'MON15',
 'MON16',
 'Suma Var',
 'Var pos neg']

De un total de 108.676 transacciones individuales, existen 31201 ruts distintos, los cuales pertenecen a 20 tipos de riesgo y pidieron creditos con 44 plazos distintos, con un promedio de monto otorgado de 41.146 MM.


Los 2000 son carterizados 

440, 6, pyme negocio que tiene riesog bajo 0,

In [11]:
df_cliente_pyme.groupby("rut_clie").count()

,Periodo,fec_info,nom_clie,cli_cat,nom_cli_cat,id_univ,cli_cat_sub,nom_sub_cat,opers,fec_otorg,...,MON9,MON10,MON11,MON12,MON13,MON14,MON15,MON16,Suma Var,Var pos neg
rut_clie,,,,,,,,,,,,,,,,,,,,,
586078,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1292399,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
1403654,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
1457776,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
1775485,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2062336,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
2284350,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
2347607,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
2441140,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2546159,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2617654,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2630255,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2642667,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2744065,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2770391,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
2856110,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
2964385,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
3040637,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3046805,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3075651,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3146592,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3149108,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3170547,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
3237722,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
3263964,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3296754,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
3317452,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3320590,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
3333537,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3344744,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99595490,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
99596200,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
99596580,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
99596590,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
99596770,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
99597220,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
99597380,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
99598320,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
99598670,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
99599180,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
99599860,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
200505517,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
200509540,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
405587340,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
443730440,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
452660276,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
452835340,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
453183276,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
456070052,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
456084052,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
456647200,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
462196708,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
462202708,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
465183212,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
467617340,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
469045512,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
470394708,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
490016172,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
496067168,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
496072052,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [13]:
df_cliente_pyme.groupby("perfil_riesgo").count()

,Periodo,fec_info,rut_clie,nom_clie,cli_cat,nom_cli_cat,id_univ,cli_cat_sub,nom_sub_cat,opers,...,MON9,MON10,MON11,MON12,MON13,MON14,MON15,MON16,Suma Var,Var pos neg
perfil_riesgo,,,,,,,,,,,,,,,,,,,,,
1,747,747,747,747,747,747,747,747,747,747,...,747,747,747,747,747,747,747,747,747,747
2,1597,1597,1597,1597,1597,1597,1597,1597,1597,1597,...,1597,1597,1597,1597,1597,1597,1597,1597,1597,1597
3,2558,2558,2558,2558,2558,2558,2558,2558,2558,2558,...,2558,2558,2558,2558,2558,2558,2558,2558,2558,2558
4,5243,5243,5243,5243,5243,5243,5243,5243,5243,5243,...,5243,5243,5243,5243,5243,5243,5243,5243,5243,5243
5,9240,9240,9240,9240,9240,9240,9240,9240,9240,9240,...,9240,9240,9240,9240,9240,9240,9240,9240,9240,9240
6,11195,11195,11195,11195,11195,11195,11195,11195,11195,11195,...,11195,11195,11195,11195,11195,11195,11195,11195,11195,11195
7,9981,9981,9981,9981,9981,9981,9981,9981,9981,9981,...,9981,9981,9981,9981,9981,9981,9981,9981,9981,9981
8,1523,1523,1523,1523,1523,1523,1523,1523,1523,1523,...,1523,1523,1523,1523,1523,1523,1523,1523,1523,1523
11,978,978,978,978,978,978,978,978,978,978,...,978,978,978,978,978,978,978,978,978,978
12,130,130,130,130,130,130,130,130,130,130,...,130,130,130,130,130,130,130,130,130,130
13,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,25
14,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
23,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
25,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
26,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
30,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
71,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
72,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
73,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2000,65447,65447,65447,65447,65447,65447,65447,65447,65447,65447,...,65447,65447,65447,65447,65447,65447,65447,65447,65447,65447

In [14]:
df_cliente_pyme.groupby("plazo").count()

,Periodo,fec_info,rut_clie,nom_clie,cli_cat,nom_cli_cat,id_univ,cli_cat_sub,nom_sub_cat,opers,...,MON9,MON10,MON11,MON12,MON13,MON14,MON15,MON16,Suma Var,Var pos neg
plazo,,,,,,,,,,,,,,,,,,,,,
10 Años,76,76,76,76,76,76,76,76,76,76,...,76,76,76,76,76,76,76,76,76,76
12 Años,257,257,257,257,257,257,257,257,257,257,...,257,257,257,257,257,257,257,257,257,257
12 meses,35,35,35,35,35,35,35,35,35,35,...,35,35,35,35,35,35,35,35,35,35
13 - 18,821,821,821,821,821,821,821,821,821,821,...,821,821,821,821,821,821,821,821,821,821
13 a 15 años,281,281,281,281,281,281,281,281,281,281,...,281,281,281,281,281,281,281,281,281,281
13 a 24,9559,9559,9559,9559,9559,9559,9559,9559,9559,9559,...,9559,9559,9559,9559,9559,9559,9559,9559,9559,9559
15 Años,65,65,65,65,65,65,65,65,65,65,...,65,65,65,65,65,65,65,65,65,65
16 a 20 años,75,75,75,75,75,75,75,75,75,75,...,75,75,75,75,75,75,75,75,75,75
180 - 364,1280,1280,1280,1280,1280,1280,1280,1280,1280,1280,...,1280,1280,1280,1280,1280,1280,1280,1280,1280,1280
19 - 24,256,256,256,256,256,256,256,256,256,256,...,256,256,256,256,256,256,256,256,256,256
24 meses,313,313,313,313,313,313,313,313,313,313,...,313,313,313,313,313,313,313,313,313,313
25 a 36,5265,5265,5265,5265,5265,5265,5265,5265,5265,5265,...,5265,5265,5265,5265,5265,5265,5265,5265,5265,5265
3 a 12,5938,5938,5938,5938,5938,5938,5938,5938,5938,5938,...,5938,5938,5938,5938,5938,5938,5938,5938,5938,5938
30 - 89,744,744,744,744,744,744,744,744,744,744,...,744,744,744,744,744,744,744,744,744,744
36 meses,823,823,823,823,823,823,823,823,823,823,...,823,823,823,823,823,823,823,823,823,823
37 a 48,4886,4886,4886,4886,4886,4886,4886,4886,4886,4886,...,4886,4886,4886,4886,4886,4886,4886,4886,4886,4886
48 meses,1337,1337,1337,1337,1337,1337,1337,1337,1337,1337,...,1337,1337,1337,1337,1337,1337,1337,1337,1337,1337
49 a 60,1436,1436,1436,1436,1436,1436,1436,1436,1436,1436,...,1436,1436,1436,1436,1436,1436,1436,1436,1436,1436
5 Años,50,50,50,50,50,50,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
5 a 8 años,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
5 años,75,75,75,75,75,75,75,75,75,75,...,75,75,75,75,75,75,75,75,75,75
6 Años,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
6 a 8 años,132,132,132,132,132,132,132,132,132,132,...,132,132,132,132,132,132,132,132,132,132
60 meses,683,683,683,683,683,683,683,683,683,683,...,683,683,683,683,683,683,683,683,683,683
61 a 96,393,393,393,393,393,393,393,393,393,393,...,393,393,393,393,393,393,393,393,393,393
61+,521,521,521,521,521,521,521,521,521,521,...,521,521,521,521,521,521,521,521,521,521
7-12,1893,1893,1893,1893,1893,1893,1893,1893,1893,1893,...,1893,1893,1893,1893,1893,1893,1893,1893,1893,1893
8 Años,36,36,36,36,36,36,36,36,36,36,...,36,36,36,36,36,36,36,36,36,36
9 Años,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
9 a 12 años,1183,1183,1183,1183,1183,1183,1183,1183,1183,1183,...,1183,1183,1183,1183,1183,1183,1183,1183,1183,1183
90 - 179,987,987,987,987,987,987,987,987,987,987,...,987,987,987,987,987,987,987,987,987,987
96+,170,170,170,170,170,170,170,170,170,170,...,170,170,170,170,170,170,170,170,170,170
<= 6,3391,3391,3391,3391,3391,3391,3391,3391,3391,3391,...,3391,3391,3391,3391,3391,3391,3391,3391,3391,3391
>30 y < 90 días,26459,26459,26459,26459,26459,26459,26459,26459,26459,26459,...,26459,26459,26459,26459,26459,26459,26459,26459,26459,26459
>= 180 y <365 días,1341,1341,1341,1341,1341,1341,1341,1341,1341,1341,...,1341,1341,1341,1341,1341,1341,1341,1341,1341,1341
>= 25,244,244,244,244,244,244,244,244,244,244,...,244,244,244,244,244,244,244,244,244,244
>= 365,2065,2065,2065,2065,2065,2065,2065,2065,2065,2065,...,2065,2065,2065,2065,2065,2065,2065,2065,2065,2065
>= 365 y <540 días,159,159,159,159,159,159,159,159,159,159,...,159,159,159,159,159,159,159,159,159,159
>= 90 y < 180 días,4587,4587,4587,4587,4587,4587,4587,4587,4587,4587,...,4587,4587,4587,4587,4587,4587,4587,4587,4587,4587
>=540 y <730 días,85,85,85,85,85,85,85,85,85,85,...,85,85,85,85,85,85,85,85,85,85
>=730 días,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
Hasta 1 Año,173,173,173,173,173,173,173,173,173,173,...,173,173,173,173,173,173,173,173,173,173
Hasta 30 días,8871,8871,8871,8871,8871,8871,8871,8871,8871,8871,...,8871,8871,8871,8871,8871,8871,8871,8871,8871,8871
Hasta 89 días,7258,7258,7258,7258,7258,7258,7258,7258,7258,7258,...,7258,7258,7258,7258,7258,7258,7258,7258,7258,7258

In [17]:
df_cliente_pyme["mto_otorg"].mean()

41.14658008642207

In [1]:
df_cliente_pyme.groupby("GLOSA ACTIVIDAD CIIU").count()

NameError: name 'df_cliente_pyme' is not defined