In [ ]:
import os
pwd = os.cmd()

Banco Santander

In [2]:
import sqlite3 as lite
import pandas
import matplotlib.pyplot as plt
import os

In [3]:
# Coneccion bd
filename = '/Users/diiru/Desktop/Santander'
conector = lite.connect(filename+ ".db")

In [23]:
# Informacion Clientes con garantia
df_cliente_pyme = pandas.read_excel('Pyme/Cliente PYME solo Gtia.xlsx')

In [24]:
df_cliente_pyme

,RUT_CORTO,Dv,NÂ°Grtia,Ampl Grtia,Desc Tipo Grtia,F Const Grtia,Fec Inic Grtia,Fec Vcto Grtia,Imp Limt Grtia,Mon,Unnamed: 10
0,9458959,2,40,S,PRENDA SIN DESPLAZAMIENTO GEN,1996-04-22,1996-04-22,2011-11-28,3300000.0,CLP,NaN
1,5741391,3,161,S,PRENDA SIN DESPLAZAMIENTO GEN,1996-08-28,1996-08-28,9999-12-31,3550847.0,CLP,NaN
2,7173489,7,205,S,PRENDA SIN DESPLAZAMIENTO GEN,1996-11-15,1996-11-15,2009-07-14,2940678.0,CLP,NaN
3,3916796,4,232,S,PRENDA SIN DESPLAZAMIENTO GEN,1996-11-25,1996-11-25,2009-07-14,3974575.0,CLP,NaN
4,9223936,5,247,S,PRENDA SIN DESPLAZAMIENTO GEN,1996-12-12,1996-12-12,9999-12-31,1.0,CLP,NaN
5,12464316,3,349,S,PRENDA SIN DESPLAZAMIENTO GEN,1997-03-13,1997-03-13,9999-12-31,2940678.0,CLP,NaN
6,6872280,2,487,S,PRENDA SIN DESPLAZAMIENTO GEN,1997-05-14,1997-05-14,9999-12-31,2000000.0,CLP,NaN
7,8853454,9,693,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-04-27,1999-04-27,2011-11-28,7068200.0,CLP,NaN
8,12222129,6,773,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-06-01,1999-06-01,2009-07-14,3300000.0,CLP,NaN
9,10718874,6,797,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-06-15,1999-06-15,2011-11-28,3200000.0,CLP,NaN
10,7890735,5,805,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-06-16,1999-06-16,9999-12-31,1.0,CLP,NaN
11,12723223,7,831,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-06-16,1999-06-16,9999-12-31,3990000.0,CLP,NaN
12,8128788,0,835,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-06-16,1999-06-16,9999-12-31,4500000.0,CLP,NaN
13,10972216,2,933,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-07-21,1999-07-21,2011-11-28,7658200.0,CLP,NaN
14,13193229,4,945,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-07-29,1999-07-29,2011-11-28,2900000.0,CLP,NaN
15,14509384,8,1048,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-08-17,1999-08-17,2011-11-28,3000000.0,CLP,NaN
16,2842130,3,1082,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-08-30,1999-08-30,9999-12-31,4490000.0,CLP,NaN
17,9832859,9,1115,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-08-30,1999-08-30,9999-12-31,1600000.0,CLP,NaN
18,5899533,9,1295,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-09-23,1999-09-23,9999-12-31,3850000.0,CLP,NaN
19,8054398,0,1331,S,PRENDA SIN DESPLAZAMIENTO GEN,1999-09-29,1999-09-29,9999-12-31,1.0,CLP,NaN
20,12708533,1,1518,S,PRENDA SIN DESPLAZAMIENTO GEN,1997-09-16,1997-09-16,9999-12-31,2850000.0,CLP,NaN
21,7817525,7,1524,S,PRENDA SIN DESPLAZAMIENTO GEN,1997-09-17,1997-09-17,9999-12-31,1.0,CLP,NaN
22,6595050,2,1640,S,PRENDA SIN DESPLAZAMIENTO GEN,1997-11-14,1997-11-14,9999-12-31,5090000.0,CLP,NaN
23,4968767,2,1818,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-03-25,1998-03-25,9999-12-31,1.0,CLP,NaN
24,4112250,1,1851,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-04-30,1998-04-30,9999-12-31,7192000.0,CLP,NaN
25,6684819,1,1932,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-07-27,1998-07-27,2011-11-28,4354200.0,CLP,NaN
26,8647806,4,2000,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-07-29,1998-07-29,2011-11-28,5716800.0,CLP,NaN
27,8569044,2,2075,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-07-29,1998-07-29,9999-12-31,3990000.0,CLP,NaN
28,11543053,K,2085,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-07-29,1998-07-29,2009-07-14,3990000.0,CLP,NaN
29,12007155,6,2122,S,PRENDA SIN DESPLAZAMIENTO GEN,1998-07-30,1998-07-30,9999-12-31,3000000.0,CLP,NaN
...,...,...,...,...,...,...,...,...,...,...,...
214531,12417329,9,973021,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,16240000.0,CLP,NaN
214532,77195700,5,973024,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,64000000.0,CLP,NaN
214533,76270835,3,973025,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,4446000.0,CLP,NaN
214534,15620759,4,973026,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,40000000.0,CLP,NaN
214535,5572388,5,973027,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,9678400.0,CLP,NaN
214536,76460336,2,973028,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,60000000.0,CLP,NaN
214537,13858061,K,973030,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,31500000.0,CLP,NaN
214538,8174102,6,973031,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,8800000.0,CLP,NaN
214539,76501169,8,973035,S,HIPOTECA CREDITO HIPOTECARIO ESP,NaN,2017-04-03,9999-12-31,7904.0,UF,NaN
214540,76582092,8,973036,S,PERSONALES FIANZA LIMITADA EN MONTO GEN,2017-04-24,2017-04-28,9999-12-31,80000000.0,CLP,NaN
214541,76243405,9,973042,S,HIPOTECA CREDITO HIPOTECARIO GRAL,NaN,2017-04-03,9999-12-31,23040.0,UF,NaN
214542,76567301,1,973043,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,9000000.0,CLP,NaN
214543,76034246,7,973045,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,93100000.0,CLP,NaN
214544,76360489,6,973046,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,94500000.0,CLP,NaN
214545,76202656,2,973059,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,4920000.0,CLP,NaN
214546,9252343,8,973060,S,HIPOTECA CREDITO HIPOTECARIO ESP,NaN,2017-04-03,9999-12-31,2389.5,UF,NaN
214547,76589693,2,973062,S,HIPOTECA CREDITO HIPOTECARIO ESP,NaN,2017-04-03,9999-12-31,2018.7,UF,NaN
214548,11351041,2,973064,S,HIPOTECA CREDITO HIPOTECARIO ESP,NaN,2017-04-03,9999-12-31,6168.6,UF,NaN
214549,76000757,9,973069,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,4064000.0,CLP,NaN
214550,76556064,0,973075,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,36000000.0,CLP,NaN
214551,76066539,8,973076,S,GARANTIAS FOGAPE ESPECIFICAS,NaN,2017-04-28,9999-12-31,15350000.0,CLP,NaN
214552,76275160,7,973081,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,60000000.0,CLP,NaN
214553,10455642,6,973082,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,3150000.0,CLP,NaN
214554,78314080,2,973083,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,3720000.0,CLP,NaN
214555,76543355,K,973084,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,17977336.0,CLP,NaN
214556,76749570,6,973085,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,35000000.0,CLP,NaN
214557,76225494,8,973086,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,43568779.0,CLP,NaN
214558,76208572,0,973087,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,29400000.0,CLP,NaN
214559,76177955,9,973090,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,18635102.0,CLP,NaN
214560,76064656,3,973091,S,GARANTIAS CORFO ESPECIFICAS,NaN,2017-04-28,9999-12-31,26400000.0,CLP,NaN

In [25]:
list(df_cliente_pyme)

['RUT_CORTO',
 'Dv',
 'NÂ°Grtia',
 'Ampl Grtia',
 'Desc Tipo Grtia',
 'F Const Grtia',
 'Fec Inic Grtia',
 'Fec Vcto Grtia',
 'Imp Limt Grtia',
 'Mon',
 'Unnamed: 10']

In [36]:
# USED: df_cliente_pyme.to_sql("Cliente_Pyme", conector)

/Users/diiru/anaconda/lib/python3.5/site-packages/pandas/core/generic.py:1345: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [3]:
# Todas las transacciones de pymes en un aÃ±o
df_pyme_total = pandas.read_excel('Pyme/000 Venta 2016_2017 Pyme Negocio.xlsx')

In [4]:
df_pyme_total

,Periodo,fec_info,rut_clie,dv_clie,nom_clie,id_orden_cate,cli_cat,nom_cli_cat,id_orden_univ,id_univ,...,SegDesgravamenPrima,SegCesantia,SegCesantiaPrima,SegVida,SegVidaPrima,SegCruzable,SegCampMDP,SegTramoCred,FecAct,RowId
0,201611,20161130,76054295,4,MUNIZAGA Y COMPANIA LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596306
1,201611,20161130,76846580,0,FONOAUD ASOC MARIO CAMPOS P Y CIA LTDA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596307
2,201611,20161130,9695335,6,ARCE MARDONES JORGE ALEJANDRO,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596308
3,201611,20161130,77400880,2,ASESORIAS INTEGRALES DEL PINO LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596309
4,201611,20161130,13119745,4,MUNDACA ROJAS AUGUSTO,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596310
5,201611,20161130,76456244,5,CASUSO DESIGNS SPA,11,810,Negocio,160000,Negocio,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596312
6,201611,20161130,76116208,K,IMPORTADORA Y EXPORTADORA REINHARDT SOLA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596313
7,201611,20161130,76012058,8,JOSE SALVADOR HUAIQUIL HUAIQUIL ARRIENDO,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596314
8,201611,20161130,6157241,4,FLORES BORQUEZ LUIS ALEJANDRO,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596315
9,201611,20161130,76575774,6,TRANSPORTES ARIEL RAMSES LIMITADA,11,810,Negocio,160000,Negocio,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596350
10,201611,20161130,16126738,4,DIAZ DURAN FERNANDO LORENZO,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596352
11,201611,20161130,96540140,7,REMAK S A,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596354
12,201611,20161130,78604950,4,VILLABLANCA INDUSTRIAL LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596355
13,201611,20161130,78604950,4,VILLABLANCA INDUSTRIAL LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596356
14,201611,20161130,77696640,1,SOCIEDAD COMERCIAL NASA LIMITADA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596379
15,201611,20161130,76498120,0,CORTES Y CIA LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596380
16,201611,20161130,77641030,6,INGEQUIMICA LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596357
17,201611,20161130,6745501,0,PARIS AVALOS MARIA TEREZINA DEL ROSARIO,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596358
18,201611,20161130,76272862,1,SERVICIOS CHILE CALL SPA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596359
19,201611,20161130,76438149,1,TRANSPORTES FREE LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596360
20,201611,20161130,79662560,0,MILLALEMU Y CIA LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596361
21,201611,20161130,79662560,0,MILLALEMU Y CIA LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596362
22,201611,20161130,79662560,0,MILLALEMU Y CIA LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596363
23,201611,20161130,10024017,3,ERAZO GONZALEZ MANUEL ENRIQUE,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596366
24,201611,20161130,5119587,6,BAUTISTA CARDENAS LINCOYAN GREGORIO,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596369
25,201601,20160129,76059631,0,ANDRES CACERES LOPEZ OBRAS DE INGENIERI,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-02-02 17:59:01.007,10714925
26,201601,20160129,76244189,6,IMALAB S A,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-02-02 17:59:01.007,10714929
27,201611,20161130,76056096,0,TRANSPORTES TELLOMERCADO LTDA,11,810,Negocio,160000,Negocio,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596316
28,201611,20161130,76127982,3,TRANSPORTES Y SERVICIOS RAMIREZ LTDA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596318
29,201611,20161130,76162153,K,S&G SERVICIOS LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2016-12-02 16:38:35.493,15596323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108646,201705,20170518,76370156,5,TRANSPORTES ROBINSON CASANOVA FERRAT,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.113,18448874
108647,201705,20170518,76079097,4,PROD Y SERV DE APOYO IND FIVEPACK LTD,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.113,18448875
108648,201705,20170518,76115180,0,GENESIS MONTAJES INDUSTRIAL LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.113,18448947
108649,201705,20170518,76341000,5,CINGEL LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.113,18448990
108650,201705,20170518,76363247,4,SOCIEDAD DE TRANSPORTES RIPERVA LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.113,18449008
108651,201705,20170518,76475494,8,PENETRON CHILE SPA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449123
108652,201705,20170518,76475494,8,PENETRON CHILE SPA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449124
108653,201705,20170518,76475494,8,PENETRON CHILE SPA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449125
108654,201705,20170518,76197056,9,COMERCIALIZADORA SAN FRANCIS SPA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449128
108655,201705,20170518,76197056,9,COMERCIALIZADORA SAN FRANCIS SPA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449129
108656,201705,20170518,76202018,1,SER DE ING ARQUITECTURA Y MONTAJES LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449181
108657,201705,20170518,76623400,3,CONSTRUCTORA V Y V LIMITADA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449182
108658,201705,20170518,76623400,3,CONSTRUCTORA V Y V LIMITADA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449183
108659,201705,20170518,76623400,3,CONSTRUCTORA V Y V LIMITADA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449184
108660,201705,20170518,76623400,3,CONSTRUCTORA V Y V LIMITADA,13,820,Pyme,170010,Pyme 1,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449185
108661,201705,20170518,76017940,K,CORTE Y PLEGADO CONMETAL LIMITADA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449186
108662,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449189
108663,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449190
108664,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449191
108665,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449192
108666,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449193
108667,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449194
108668,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449195
108669,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449196
108670,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449197
108671,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449198
108672,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449199
108673,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449200
108674,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449201
108675,201705,20170518,82125200,8,SOC CONTS FIERRO Y PLAST LTDA,13,820,Pyme,170020,Pyme 2,...,0.0,0,0.0,0,0.0,0,NaN,NaN,2017-05-19 13:11:11.220,18449202

In [5]:
list(df_pyme_total)

['Periodo',
 'fec_info',
 'rut_clie',
 'dv_clie',
 'nom_clie',
 'id_orden_cate',
 'cli_cat',
 'nom_cli_cat',
 'id_orden_univ',
 'id_univ',
 'cli_cat_sub',
 'nom_sub_cat',
 'id_orden_sgmto_conc',
 'id_sgmto_conc',
 'opers',
 'fec_otorg',
 'aÃ±o_otorg',
 'mes_otorg',
 'dia_otorg',
 'suc_fus_nueva',
 'nom_suc_fus',
 'zona_nueva',
 'Zonal',
 'grp_suc',
 'mto_otorg',
 'prod',
 'sub_prod',
 'cta_actual',
 'cod_ctr',
 'rut_ejec_gest',
 'dv_ejec_gest',
 'nom_ejec_gest',
 'cargo_ejec_gest_rrhh',
 'cargo_conc_gest',
 'suc_gest_ejec',
 'nom_suc_gest',
 'suc_gpo',
 'nom_suc_gpo_gest',
 'suc_grp3_gest',
 'nom_suc_grp3_gest',
 'suc_grp4_gest',
 'nom_suc_grp4_gest',
 'zona_nueva_gest',
 'cod_ctr_vta',
 'nom_ejec_gest_vta',
 'RutVdor',
 'id_orden_prod',
 'id_prod_conc',
 'extin_cdto',
 'plazo_meses',
 'tasa_act',
 'tasa_transf',
 'Tipo_conta',
 'spread',
 'margen_b',
 'id_plazo',
 'id_tramo',
 'id_tasa',
 'grp',
 'NOM_GRP',
 'tasa_0',
 'tasa_1',
 'tasa_1_tarifado',
 'modelo_id_riesgo',
 'perfil_riesgo',
 'ajuste_max',
 'descuento',
 'plazo',
 'tramo',
 'n_cuotas_pact',
 'plazos_dias',
 'smneg',
 'tmk',
 'internet',
 'atm',
 'observaciÃ³n',
 'marca_eliminar',
 'marca_prod_visible',
 'tipo_flujo',
 'cod_mda_sbif',
 'marca_desface',
 'n_pagare',
 'id_func',
 'fecha_otorgamiento',
 'tipo_camb_reaj',
 'tipo_camb_mx',
 'origen',
 'mto_tas_Act_inv',
 'mto_tas_1_inv',
 'prod_gsc',
 'peso_ctr',
 'id_elimina',
 'observ_elimina',
 'plan',
 'concepto',
 'concepto_especifico',
 'Marca_funcionario',
 'Marca_Conta',
 'Marca_CampaÃ±a',
 'Marca_Renegociados',
 'Marca_Alivio',
 'Marca_Carterizado',
 'MarcaCanal',
 'MarcaFFVV',
 'MarcaVOX',
 'MarcaATM',
 'MarcaINT',
 'RutFunFFVV',
 'DvFunFFVV',
 'FecAltaCtaCte',
 'NroDiasCtaCte',
 'RutFunVOX',
 'DvFunVOX',
 'CanalVOX',
 'SubCanalVOX',
 'FecDerivATM',
 'FecDerivINT',
 'McaREEOpe',
 'McaREECli',
 'DiaHabil',
 'SegDesgravamen',
 'SegDesgravamenPrima',
 'SegCesantia',
 'SegCesantiaPrima',
 'SegVida',
 'SegVidaPrima',
 'SegCruzable',
 'SegCampMDP',
 'SegTramoCred',
 'FecAct',
 'RowId']

In [39]:
print("Varianza monto otorgado: {0}".format(df_pyme_total["mto_otorg"].var()))
print("Media monto otorgado: {0}".format(df_pyme_total["mto_otorg"].mean()))

Varianza monto otorgado: 16869.684836434
Media monto otorgado: 41.146580086422304

In [39]:
df_pyme_total.groupby("id_univ")["tasa_act"].mean()

id_univ
Negocio    1.408864
Pyme       0.387222
Pyme 1     1.256486
Pyme 2     0.875920
Name: tasa_act, dtype: float64

In [44]:
df_pyme_total.groupby("id_univ")

cli_cat_sub
801    0.391444
811    1.631559
812    1.487627
813    1.640564
814    1.582301
815    1.673755
816    1.609789
821    1.501408
822    1.414001
823    1.090667
824    0.968073
825    1.522590
826    1.443963
827    1.124488
828    0.959554
829    1.523872
830    1.471862
831    1.085433
832    0.972985
833    1.287121
834    1.191237
835    1.357026
836    1.212669
837    1.422244
838    1.195420
Name: tasa_1, dtype: float64

In [41]:
df_pyme_total.groupby("id_univ")["tasa_1"].var()

id_univ
Negocio    0.188580
Pyme       0.282222
Pyme 1     0.153381
Pyme 2     0.152040
Name: tasa_1, dtype: float64

In [82]:
df_pyme_total.groupby("id_prod_conc").count()

,Periodo,fec_info,rut_clie,dv_clie,nom_clie,id_orden_cate,cli_cat,nom_cli_cat,id_orden_univ,id_univ,...,SegDesgravamenPrima,SegCesantia,SegCesantiaPrima,SegVida,SegVidaPrima,SegCruzable,SegCampMDP,SegTramoCred,FecAct,RowId
id_prod_conc,,,,,,,,,,,,,,,,,,,,,
Cdto Contingente,12855,12855,12855,12855,12855,12855,12855,12855,12855,12855,...,12855,12855,12855,12855,12855,12855,0,0,12855,12855
Cdto Imp-Exp,9927,9927,9927,9927,9927,9927,9927,9927,9927,9927,...,9927,9927,9927,9927,9927,9927,0,0,9927,9927
Comerciales,11312,11312,11312,11312,11312,11312,11312,11312,11312,11312,...,11312,11312,11312,11312,11312,11312,0,0,11312,11312
Comerciales cuotas,13988,13988,13988,13988,13988,13988,13988,13988,13988,13988,...,13988,13988,13988,13988,13988,13988,0,0,13988,13988
Corfo,12454,12454,12454,12454,12454,12454,12454,12454,12454,12454,...,12454,12454,12454,12454,12454,12454,0,0,12454,12454
CrÃ©ditos consumos,840,840,840,840,840,840,840,840,840,840,...,840,840,840,840,840,840,0,0,840,840
Factoring,35311,35311,35311,35311,35311,35311,35311,35311,35311,35311,...,35311,35311,35311,35311,35311,35311,0,0,35311,35311
Fines generales,1277,1277,1277,1277,1277,1277,1277,1277,1277,1277,...,1277,1277,1277,1277,1277,1277,0,0,1277,1277
Fogape,5781,5781,5781,5781,5781,5781,5781,5781,5781,5781,...,5781,5781,5781,5781,5781,5781,0,0,5781,5781
Leasing,3932,3932,3932,3932,3932,3932,3932,3932,3932,3932,...,3932,3932,3932,3932,3932,3932,0,0,3932,3932
Refinanciados Corfo,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,0,0,12,12
Tarjeta Consumo on line,390,390,390,390,390,390,390,390,390,390,...,390,390,390,390,390,390,0,0,390,390
Vivienda,597,597,597,597,597,597,597,597,597,597,...,597,597,597,597,597,597,0,0,597,597

In [80]:

df_pyme_total.groupby("id_prod_conc")["tasa_act"].mean().reset_index(name='tasa').sort_values(['tasa'], ascending=True)

               id_prod_conc      tasa
7           Fines generales  0.347814
12                 Vivienda  0.361369
0          Cdto Contingente  0.630821
1              Cdto Imp-Exp  0.654166
9                   Leasing  0.793158
6                 Factoring  1.073314
5         CrÃ©ditos consumos  1.093392
2               Comerciales  1.162076
10      Refinanciados Corfo  1.171667
3        Comerciales cuotas  1.285644
4                     Corfo  1.357418
8                    Fogape  1.462553
11  Tarjeta Consumo on line  1.798795

In [27]:
df_pyme_total["tasa_1"].mean()

1.1714824570284217

In [29]:
df_pyme_total["tasa_1"].var()

0.21343897221463845

In [28]:
df_pyme_total["spread"].mean()

0.7158532966831844

In [32]:
df_pyme_total["mto_otorg"].max()

21497.543930340002

In [34]:
# Que sucursales dan mas creditos ?
repetidos = pandas.DataFrame()
query_sql = '''SELECT nom_suc_gest, Count(*) FROM Santander GROUP BY nom_suc_gest ORDER BY Count(*) ASC'''
repetidos = repetidos.append(pandas.read_sql(query_sql, conector))

In [35]:
repetidos

                             nom_suc_gest  Count(*)
0                                    None         1
1                     Ahumada II Personas         1
2                         Ahumada IV BBPP         1
3                              Befeosorno         1
4                      Bfc Vina Villanelo         1
5                               Boulevard         1
6                                  CALAMA         1
7                   CAMPUS UNIV. DE TALCA         1
8                     CLINICA SANTA MARIA         1
9                        COSTANERA CENTER         1
10                  Centro De Inversiones         1
11        Centro de Empresas Puerto Montt         1
12        Centro de Empresas Santiago Sur         1
13        Centro de Empresas ViÃ±a del Mar         1
14                               Chicureo         1
15                   Concepcion Chacabuco         1
16                          G. Fuenzalida         1
17                                   LIDO         1
18                          LOS TRAPENSES         1
19                            La Cisterna         1
20                             La Florida         1
21                             Linares Bf         1
22                           Los CastaÃ±os         1
23                           Luis Pasteur         1
24                                MACHALI         1
25                         Mesa De Dinero         1
26                 NUCLEO EMP TALCA PLAZA         1
27                               Nataniel         1
28                    Nueva Los Dominicos         1
29                                 OSORNO         1
..                                    ...       ...
394                     Antofagasta Plaza      1167
395                    Isidora Goyenechea      1182
396                          Ricardo Lyon      1186
397                          Plaza Bulnes      1225
398                           Irarrazaval      1242
399                        QUILLOTA PLAZA      1258
400                   Pedro Aguirre Cerda      1288
401  Candelaria Goyenechea  Empresas Grp1      1346
402                              La Bolsa      1348
403         Concha Y Toro Centro Empresas      1352
404                      Valdivia Empresa      1439
405                      Rodrigo De Araya      1456
406                             Apumanque      1508
407                           Ahumada III      1529
408                      Americo Vespucio      1557
409                              Rancagua      1621
410                   Concepcion Catedral      1667
411                               Chillan      1696
412                                 Renca      1718
413                            ViÃ±a Plaza      1722
414                            Concepcion      1754
415                                Temuco      1828
416                          Osorno Plaza      1883
417                          PRINCIPAL IV      2082
418                          Puerto Montt      2119
419                             San Diego      2229
420                                Curico      2246
421                          Temuco Plaza      2468
422                              Recoleta      2489
423                     Centro Banca Pyme      2969

[424 rows x 2 columns]

In [45]:
unicos = pandas.DataFrame()
query_sql = '''SELECT cli_cat_sub FROM Santander WHERE id_univ == "Pyme"'''
unicos = unicos.append(pandas.read_sql(query_sql, conector))

In [46]:
unicos

    cli_cat_sub
0           801
1           801
2           801
3           801
4           801
5           801
6           801
7           801
8           801
9           801
10          801
11          801
12          801
13          801
14          801
15          801
16          801
17          801
18          801
19          801
20          801
21          801
22          801
23          801
24          801
25          801
26          801
27          801
28          801
29          801
30          801
31          801
32          801
33          801
34          801
35          801
36          801
37          801
38          801
39          801
40          801
41          801
42          801
43          801
44          801

Tipo de producto,
monto mayor a 5mil UF, 132 palos

Segmento


spread x monto/ monto total
tasa x monto




producto, segmento y menor a 5k

In [ ]:
# Cruce; cuantos creditos se le dan a gente con credito ?
cruce = pandas.DataFrame()
query_sql = '''SELECT COUNT(*) FROM Santander as SAN, Cliente_Pyme as CLI WHERE SAN.rut_clie LIKE CLI.RUT_CORTO '''
cruce = cruce.append(pandas.read_sql(query_sql, conector))

In [ ]:
cruce